if(NOT SOURCE_BUILD_CLIENTMOD)
  message(FATAL_ERROR "SOURCE_BUILD_CLIENTMOD_GRAPHICS requires SOURCE_BUILD_CLIENTMOD")
endif()
execute_process(COMMAND "${Python3_EXECUTABLE}" "${CMAKE_CURRENT_SOURCE_DIR}/scripts/clientmod_manifest.py" --graphics RESULT_VARIABLE result)
if(NOT result EQUAL 0)
  message(FATAL_ERROR "Original graphical source manifest changed")
endif()
execute_process(COMMAND "${Python3_EXECUTABLE}" "${CMAKE_CURRENT_SOURCE_DIR}/scripts/prepare_clientmod_graphics.py"
  "${CLIENTMOD_UPSTREAM}" "${CLIENTMOD_ROOT}" "${SOURCE_UPSTREAM}" "${SOURCE_ROOT}" RESULT_VARIABLE result)
if(NOT result EQUAL 0)
  message(FATAL_ERROR "Could not prepare original graphical modules")
endif()
file(READ "${CMAKE_CURRENT_SOURCE_DIR}/cmake/clientmod-graphics-files.json" manifest)
set(graphical_targets)
foreach(module IN ITEMS engine materialsystem shaderapidx9 togl inputsystem launcher video_services datamodel appframework filesystem_stdio datacache studiorender vphysics)
  set(sources)
  string(JSON count LENGTH "${manifest}" modules ${module} source)
  math(EXPR last "${count}-1")
  foreach(index RANGE 0 ${last})
    string(JSON path GET "${manifest}" modules ${module} source ${index})
    if(NOT path STREQUAL "public/tier0/memoverride.cpp")
      list(APPEND sources "${CLIENTMOD_ROOT}/${path}")
    endif()
  endforeach()
  add_library(clientmod_${module} STATIC ${sources})
  set_target_properties(clientmod_${module} PROPERTIES CXX_STANDARD 14 POSITION_INDEPENDENT_CODE ON)
  if(SOURCE_BUILD_CLIENTMOD_RUNTIME)
    set_target_properties(clientmod_${module} PROPERTIES CXX_VISIBILITY_PRESET hidden VISIBILITY_INLINES_HIDDEN ON)
    target_compile_options(clientmod_${module} PRIVATE -U_STATIC_LINKED)
  endif()
  target_link_libraries(clientmod_${module} PRIVATE source_settings)
  target_compile_options(clientmod_${module} PRIVATE -w)
  target_compile_definitions(clientmod_${module} PRIVATE USE_SDL=1 NO_STEAM=1 DISABLE_STEAM=1
    DX_TO_GL_ABSTRACTION=1 TOGLES=1 GL_GLEXT_PROTOTYPES=1 MESA_EGL_NO_X11_HEADERS=1 VERSION_SAFE_STEAM_API_INTERFACES=1)
  target_include_directories(clientmod_${module} BEFORE PRIVATE "${CLIENTMOD_ROOT}/graphics-compat")
  string(JSON count LENGTH "${manifest}" modules ${module} includes)
  math(EXPR last "${count}-1")
  foreach(index RANGE 0 ${last})
    string(JSON path GET "${manifest}" modules ${module} includes ${index})
    if(path MATCHES "^(public|ivp)($|/)")
      target_include_directories(clientmod_${module} PRIVATE "${SOURCE_ROOT}/${path}")
    else()
      target_include_directories(clientmod_${module} PRIVATE "${CLIENTMOD_ROOT}/${path}")
    endif()
  endforeach()
  target_include_directories(clientmod_${module} PRIVATE "${CLIENTMOD_ROOT}/common" "${CMAKE_CURRENT_SOURCE_DIR}/src/source"
    "${SOURCE_UPSTREAM}/thirdparty/SDL-src/include" "${SOURCE_UPSTREAM}/thirdparty/SDL-src/src/video/khronos"
    "${SOURCE_UPSTREAM}/thirdparty/curl/include" "${SOURCE_UPSTREAM}/thirdparty/libjpeg"
    "${SOURCE_UPSTREAM}/thirdparty/openal-soft/include")
  list(APPEND graphical_targets clientmod_${module})
endforeach()
# The game DLL and engine subsystems are part of the full runtime profile.
if(SOURCE_BUILD_CLIENTMOD_RUNTIME)
  foreach(module server soundemittersystem scenefilecache)
    set(sources)
    string(JSON count LENGTH "${manifest}" modules ${module} source)
    math(EXPR last "${count}-1")
    foreach(index RANGE 0 ${last})
      string(JSON path GET "${manifest}" modules ${module} source ${index})
      if(NOT path STREQUAL "public/tier0/memoverride.cpp")
        list(APPEND sources "${CLIENTMOD_ROOT}/${path}")
      endif()
    endforeach()
    add_library(clientmod_${module} STATIC ${sources})
    set_target_properties(clientmod_${module} PROPERTIES CXX_STANDARD 14 POSITION_INDEPENDENT_CODE ON
      CXX_VISIBILITY_PRESET hidden VISIBILITY_INLINES_HIDDEN ON)
    target_link_libraries(clientmod_${module} PRIVATE source_settings)
    target_compile_options(clientmod_${module} PRIVATE -w -U_STATIC_LINKED)
    target_compile_definitions(clientmod_${module} PRIVATE NO_STEAM=1 DISABLE_STEAM=1
      VERSION_SAFE_STEAM_API_INTERFACES=1 USE_SDL=1)
    string(JSON count LENGTH "${manifest}" modules ${module} includes)
    math(EXPR last "${count}-1")
    foreach(index RANGE 0 ${last})
      string(JSON path GET "${manifest}" modules ${module} includes ${index})
      if(NOT path MATCHES "^public($|/)")
        target_include_directories(clientmod_${module} PRIVATE "${CLIENTMOD_ROOT}/${path}")
      endif()
    endforeach()
    string(JSON count LENGTH "${manifest}" modules ${module} defines)
    if(count GREATER 0)
      math(EXPR last "${count}-1")
      foreach(index RANGE 0 ${last})
        string(JSON define GET "${manifest}" modules ${module} defines ${index})
        target_compile_definitions(clientmod_${module} PRIVATE "${define}")
      endforeach()
    endif()
    list(APPEND graphical_targets clientmod_${module})
  endforeach()
endif()
target_compile_definitions(clientmod_engine PRIVATE ENGINE_DLL=1 VERSION_SAFE_STEAM_API_INTERFACES=1 USE_BREAKPAD_HANDLER=1)
target_compile_definitions(clientmod_materialsystem PRIVATE DEFINE_MATERIALSYSTEM_INTERFACE=1 MATERIALSYSTEM_EXPORTS=1)
target_compile_definitions(clientmod_shaderapidx9 PRIVATE SHADER_DLL_EXPORT=1 SHADERAPIDX9=1 FAST_MATERIALVAR_ACCESS=1)
target_compile_definitions(clientmod_togl PRIVATE TOGL_DLL_EXPORT=1)
target_compile_definitions(clientmod_launcher PRIVATE LAUNCHERONLY=1)
target_compile_definitions(clientmod_studiorender PRIVATE STUDIORENDER_EXPORTS=1)
target_compile_definitions(clientmod_vphysics PRIVATE "$<$<CONFIG:Debug>:DEBUG=1>" VPHYSICS_EXPORTS=1 HAVANA_CONSTRAINTS=1 HAVOK_MOPP=1 IVP_VERSION_SDK=1)
target_include_directories(clientmod_vphysics PRIVATE "${SOURCE_ROOT}/ivp/ivp_intern" "${SOURCE_ROOT}/ivp/havana/havok")
add_custom_target(clientmod_graphics_compile_check DEPENDS ${graphical_targets})
