# Strict link profile for separate original modules. This profile does not yet
# switch the iOS application's Play action away from its existing preview.
if(NOT SOURCE_BUILD_CLIENTMOD_GRAPHICS)
  message(FATAL_ERROR "SOURCE_BUILD_CLIENTMOD_RUNTIME requires graphical modules")
endif()
set(CMAKE_POLICY_VERSION_MINIMUM 3.5)
if(APPLE)
  enable_language(OBJC)
endif()
if(CMAKE_SYSTEM_NAME STREQUAL "iOS")
  # The pinned SDL CMake predates CMAKE_SYSTEM_NAME=iOS detection.
  set(IOS TRUE)
  set(SDL_VIDEO_COCOA OFF CACHE BOOL "" FORCE)
  set(SDL_VIDEO_VULKAN OFF CACHE BOOL "" FORCE)
endif()
set(SDL_SHARED ON CACHE BOOL "" FORCE)
set(SDL_STATIC OFF CACHE BOOL "" FORCE)
set(SDL_TEST OFF CACHE BOOL "" FORCE)
foreach(feature X11 WAYLAND KMSDRM RPI ALSA PULSEAUDIO JACK SNDIO)
  set(SDL_${feature} OFF CACHE BOOL "" FORCE)
endforeach()
add_subdirectory("${SOURCE_UPSTREAM}/thirdparty/SDL-src" clientmod-deps/SDL EXCLUDE_FROM_ALL)
if(CMAKE_SYSTEM_NAME STREQUAL "iOS")
  # A continuously serviced UIKit run-loop source must not starve the original
  # engine loop. Leave queued events for the next pump; retain SDL's context restore.
  set(ios_event_source "${CMAKE_CURRENT_BINARY_DIR}/clientmod-sdl/SDL_uikitevents.m")
  execute_process(COMMAND "${Python3_EXECUTABLE}" "${CMAKE_CURRENT_SOURCE_DIR}/scripts/prepare_clientmod_sdl.py"
    "${SOURCE_UPSTREAM}/thirdparty/SDL-src" "${ios_event_source}" RESULT_VARIABLE result)
  if(NOT result EQUAL 0)
    message(FATAL_ERROR "Could not prepare pinned SDL UIKit event pump")
  endif()
  get_target_property(sdl_sources SDL2 SOURCES)
  set(patched_sdl_sources)
  set(ios_event_replacements 0)
  foreach(source IN LISTS sdl_sources)
    if(source MATCHES "(^|/)SDL_uikitevents\\.m$")
      list(APPEND patched_sdl_sources "${ios_event_source}")
      math(EXPR ios_event_replacements "${ios_event_replacements} + 1")
    else()
      list(APPEND patched_sdl_sources "${source}")
    endif()
  endforeach()
  if(NOT ios_event_replacements EQUAL 1)
    message(FATAL_ERROR "Expected one original SDL UIKit event source")
  endif()
  set_property(TARGET SDL2 PROPERTY SOURCES "${patched_sdl_sources}")
endif()
if(APPLE)
  get_target_property(sdl_sources SDL2 SOURCES)
  foreach(source IN LISTS sdl_sources)
    if(source MATCHES "\\.m$")
      set_source_files_properties(${source} DIRECTORY "${SOURCE_UPSTREAM}/thirdparty/SDL-src"
        PROPERTIES LANGUAGE OBJC)
    endif()
  endforeach()
  # Pinned SDL uses C89-style warning enforcement even in its UIKit C99 code.
  target_compile_options(SDL2 PRIVATE -Wno-error=declaration-after-statement)
endif()
set(FT_DISABLE_ZLIB ON CACHE BOOL "" FORCE)
set(FT_DISABLE_BZIP2 ON CACHE BOOL "" FORCE)
set(FT_DISABLE_PNG ON CACHE BOOL "" FORCE)
set(FT_DISABLE_HARFBUZZ ON CACHE BOOL "" FORCE)
add_subdirectory("${SOURCE_UPSTREAM}/thirdparty/freetype" clientmod-deps/freetype EXCLUDE_FROM_ALL)
set_target_properties(freetype PROPERTIES POSITION_INDEPENDENT_CODE ON)
if(APPLE)
  # The old embedded zlib expects Carbon's Byte typedef; use the SDK's zlib.
  target_compile_definitions(freetype PRIVATE FT_CONFIG_OPTION_SYSTEM_ZLIB=1)
  target_link_libraries(freetype PRIVATE z)
endif()
get_property(all_targets DIRECTORY PROPERTY BUILDSYSTEM_TARGETS)
foreach(t IN LISTS all_targets)
  get_target_property(type ${t} TYPE)
  if(type STREQUAL "STATIC_LIBRARY")
    set_target_properties(${t} PROPERTIES POSITION_INDEPENDENT_CODE ON)
  endif()
endforeach()
foreach(module tier0 vstdlib)
  get_target_property(sources source_${module} SOURCES)
  add_library(clientmod_runtime_${module} SHARED ${sources})
  target_link_libraries(clientmod_runtime_${module} PRIVATE source_settings dl pthread)
  string(TOUPPER ${module} export)
  target_compile_definitions(clientmod_runtime_${module} PRIVATE ${export}_DLL_EXPORT=1)
  target_compile_options(clientmod_runtime_${module} PRIVATE -U_STATIC_LINKED)
  set_target_properties(clientmod_runtime_${module} PROPERTIES OUTPUT_NAME ${module}
    LIBRARY_OUTPUT_DIRECTORY "${CMAKE_CURRENT_BINARY_DIR}/clientmod-runtime" BUILD_RPATH "$ORIGIN")
endforeach()
target_compile_definitions(clientmod_runtime_tier0 PRIVATE USE_SDL=1)
target_include_directories(clientmod_runtime_tier0 PRIVATE "${SOURCE_UPSTREAM}/thirdparty/SDL-src/include")
target_link_libraries(clientmod_runtime_tier0 PRIVATE SDL2)
# Full graphical builds require helpers absent from the dedicated SDK profile.
add_library(clientmod_graphics_helpers STATIC
  "${CLIENTMOD_UPSTREAM}/tier2/riff.cpp" "${CLIENTMOD_UPSTREAM}/tier2/p4helpers.cpp"
  "${CLIENTMOD_UPSTREAM}/tier2/beamsegdraw.cpp" "${CLIENTMOD_UPSTREAM}/tier2/renderutils.cpp"
  "${CLIENTMOD_UPSTREAM}/tier2/camerautils.cpp" "${CLIENTMOD_UPSTREAM}/tier3/mdlutils.cpp"
  "${CLIENTMOD_UPSTREAM}/mathlib/bumpvects.cpp" "${CLIENTMOD_UPSTREAM}/mathlib/anorms.cpp")
target_link_libraries(clientmod_graphics_helpers PRIVATE source_settings)
target_compile_options(clientmod_graphics_helpers PRIVATE -U_STATIC_LINKED)
set_target_properties(clientmod_graphics_helpers PROPERTIES POSITION_INDEPENDENT_CODE ON)
add_library(clientmod_bzip2 STATIC
  "${CLIENTMOD_ROOT}/utils/bzip2/blocksort.c" "${CLIENTMOD_ROOT}/utils/bzip2/bzlib.c"
  "${CLIENTMOD_ROOT}/utils/bzip2/compress.c" "${CLIENTMOD_ROOT}/utils/bzip2/crctable.c"
  "${CLIENTMOD_ROOT}/utils/bzip2/decompress.c" "${CLIENTMOD_ROOT}/utils/bzip2/huffman.c"
  "${CLIENTMOD_ROOT}/utils/bzip2/randtable.c")
set_target_properties(clientmod_bzip2 PROPERTIES POSITION_INDEPENDENT_CODE ON)
target_link_libraries(clientmod_runtime_vstdlib PRIVATE source_tier1 source_mathlib clientmod_runtime_tier0)
add_library(clientmod_steam_offline STATIC "${CMAKE_CURRENT_SOURCE_DIR}/src/source/ClientModSteamOffline.cpp")
target_link_libraries(clientmod_steam_offline PRIVATE source_settings)
set_target_properties(clientmod_steam_offline PROPERTIES POSITION_INDEPENDENT_CODE ON)
set(runtime_modules)
foreach(module engine materialsystem shaderapidx9 togl inputsystem launcher video_services filesystem_stdio datacache studiorender vphysics server soundemittersystem scenefilecache client GameUI vgui2 vguimatsurface stdshader_dx9 ServerBrowser)
  add_library(clientmod_runtime_${module} SHARED "${SOURCE_ROOT}/tier1/interface.cpp")
  target_link_libraries(clientmod_runtime_${module} PRIVATE source_settings
    "$<LINK_LIBRARY:WHOLE_ARCHIVE,clientmod_${module}>"
    clientmod_runtime_tier0 clientmod_runtime_vstdlib SDL2 dl pthread)
  set(helpers source_tier1 source_tier2 source_tier3 source_mathlib source_bitmap source_vtf
    clientmod_appframework source_shaderlib source_offline clientmod_graphics_helpers clientmod_steam_offline)
  if(module MATCHES "^(client|GameUI|ServerBrowser|engine|vgui2|vguimatsurface)$")
    list(APPEND helpers clientmod_vgui_controls clientmod_matsys_controls)
  endif()
  if(module MATCHES "^(client|server)$")
    list(APPEND helpers source_particles source_dmxloader source_choreoobjects source_soundemittersystem source_scenefilecache)
  endif()
  if(module STREQUAL "filesystem_stdio")
    list(APPEND helpers source_vpklib clientmod_bzip2)
  endif()
  if(module STREQUAL "vphysics")
    list(APPEND helpers source_ivp_physics source_ivp_compactbuilder source_havana_constraints source_hk_base source_hk_math)
  endif()
  if(module STREQUAL "engine")
    list(APPEND helpers clientmod_datamodel source_dmxloader clientmod_graphics_helpers clientmod_bzip2)
  endif()
  if(module STREQUAL "vguimatsurface")
    list(APPEND helpers clientmod_vgui_surfacelib freetype)
  endif()
  if(module MATCHES "^(shaderapidx9|launcher)$")
    target_link_libraries(clientmod_runtime_${module} PRIVATE clientmod_runtime_togl)
  endif()
  if(CMAKE_SYSTEM_NAME STREQUAL "Linux")
    list(JOIN helpers "," helper_group)
    target_link_libraries(clientmod_runtime_${module} PRIVATE "$<LINK_GROUP:RESCAN,${helper_group}>")
    target_link_options(clientmod_runtime_${module} PRIVATE -Wl,--no-undefined)
  else()
    target_link_libraries(clientmod_runtime_${module} PRIVATE ${helpers})
  endif()
  set_target_properties(clientmod_runtime_${module} PROPERTIES CXX_STANDARD 14 OUTPUT_NAME ${module}
    CXX_VISIBILITY_PRESET hidden VISIBILITY_INLINES_HIDDEN ON
    LIBRARY_OUTPUT_DIRECTORY "${CMAKE_CURRENT_BINARY_DIR}/clientmod-runtime" BUILD_RPATH "$ORIGIN")
  if(module STREQUAL "ServerBrowser")
    set_target_properties(clientmod_runtime_${module} PROPERTIES OUTPUT_NAME serverbrowser)
  endif()
  list(APPEND runtime_modules clientmod_runtime_${module})
endforeach()
add_custom_target(clientmod_runtime_link_check DEPENDS ${runtime_modules})
if(APPLE)
  target_link_libraries(clientmod_runtime_vstdlib PRIVATE iconv)
  foreach(module IN LISTS runtime_modules)
    target_link_libraries(${module} PRIVATE iconv)
    set_target_properties(${module} PROPERTIES BUILD_RPATH "@loader_path" INSTALL_RPATH "@loader_path")
  endforeach()
  foreach(module tier0 vstdlib)
    set_target_properties(clientmod_runtime_${module} PROPERTIES BUILD_RPATH "@loader_path" INSTALL_RPATH "@loader_path")
  endforeach()
endif()
